# -*- coding: utf-8 -*-
"""KDD e AED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9L32W2qer594EjtTpm8LGITIHwlWfYD

## Importar Bibliotecas
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Gerar dados aleatórios e plotar um histograma (distribuição)

Gerar 30 valores (1 por dia) com minutos de 0 a 60
"""

minutospordia = np.random.randint(0,60,30)
minutospordia

ax = sns.histplot(minutospordia)
ax.set(xlabel='Minutos por Dia', ylabel="Quantidade de Vezes")
plt.show()

"""## Importar e usar uma nova biblioteca para Análise Exploratória"""

!pip install sweetviz
import sweetviz as sw

"""## Carregar um arquivo de uma base dos jogos de tênis de 2021"""

arquivo = 'https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv'

dados = pd.read_csv(arquivo)
dados

eda = sw.analyze(dados)
eda.show_html()

"""## Gerar uma matriz de correlação (de Perarson) de variáveis
Lembrando que valor 1 é a correlação direta perfeita, -1 é correlação negativa perfeita e valores próximos de zero indicam a falta de existência ou dificuldade de estabelecer correlação.
"""

mask = np.triu(np.ones_like(dados.corr(), dtype = np.bool))
mask

#HeatMap
plt.figure(figsize=(20,20))
sns.heatmap(dados.corr(), mask = mask, square = True, annot = True, vmin=-1, vmax=1)